### ISSUE TITLE
shot in the dark.

### ISSUE THREAD

**Issue by srigsby** [teran-mckinney/raru#11]
get tightVNC window open by executing `xraru firefox` (only after running  `xhost +` and `tightvncserver`) but the vnc screen opens and nothing happens. check back at the terminal...

I get the following error message:
`Could not determine HOME directory[1]    10474 killed     xraru firefox`

same failure when I use an augmented form of the suggested raru alias `env -i PATH=$PATH xraru`
`Could not determine HOME directory[1]    10531 killed     env -i PATH=$PATH xraru firefox`

would-be user here just wondering if anyone was suffering the same problem or had any light to cast.

**Comment by teran-mckinney** [comment]
Are you on the latest checkout from master? I have `$HOME` exported and believe I may have ran into the same problem at a similar point, a few commits back.

`xraru chrome` and `xraru firefox` work for me.

**Comment by srigsby** [comment]
I am on the latest checkout.  
Got it to work a few times, but there is some black magic going on relating to my vnc server (using `tightvncserver`). It can successfully launch chrome, but only once (the first time I connect to the vnc (./?)) then refuses to work again... No luck on the firefox front yet.    
 In any case thanks for the quick help.

**Comment by teran-mckinney** [comment]
Hi,

You're welcome!

That is strange. There is a specific option to allow only one VNC connection and then refuse no more. You're probably running into that. I can run multiple `xraru chrome`s at once time and haven't had a problem, but it makes a separate VNC server and client per each.

What distribution are you running? I should try it on something other than FreeBSD to make sure it works properly.

Sincerely,
Teran
